"""empty message

Revision ID: 4f69b1376c49
Revises: 0eb1d6faa3c8
Create Date: 2016-08-11 16:03:20.566583

"""

# revision identifiers, used by Alembic.
revision = '4f69b1376c49'
down_revision = '0eb1d6faa3c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('book_description', sa.String(length=240), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'book_description')
    ### end Alembic commands ###
